#!/usr/bin/env ruby

require 'net/http'

http = Net::HTTP.new('127.0.0.1', 3501)
begin
  response = http.options('/')
  if response = Net::HTTPSuccess
    exit 0
  else 
    exit 1
  end
rescue Errno::ECONNREFUSED
  exit 1
end
